# Generated by Django 3.2.3 on 2022-01-03 17:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur_regulier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=18)),
                ('tel', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mouvmt_fin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_paiemt', models.CharField(choices=[('ORD', 'Comptant'), ('ACC', 'Accompte'), ('ETA', 'Etalement'), ('SOL', 'Solde'), ('ARH', 'Arrhes')], default='ORD', max_length=3)),
                ('moyen_paiemt', models.CharField(choices=[('CB_A', 'CB Annie'), ('CB_M', 'CB Michel'), ('CBM_U', 'CV_M usage unique'), ('CBM_A', 'CV_M Abonnement'), ('DAB', 'Retrait'), ('ESP', 'Espèce'), ('CHQ', 'Cheque'), ('VRMT', 'Virement'), ('PbP', 'Pay by Phone'), ('CASM', 'CasinoMax')], default='CBM_U', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_tx', models.CharField(choices=[('UNIT', 'Tx Unitaire'), ('ABMT', 'Abonnement')], default='UNIT', max_length=4)),
                ('date_tx', models.DateField(auto_now_add=True)),
                ('fournisseur', models.CharField(max_length=12)),
                ('montant_tx', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mode_reglmnt', models.CharField(choices=[('CPT', 'au Comptant'), ('ETA', 'en Plusieurs fois'), ('CRE', 'a Credit'), ('ABO', 'par abonnement')], default='CPT', max_length=3)),
                ('nb_etalmt', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
            ],
        ),
        migrations.CreateModel(
            name='Mouvmt_courant',
            fields=[
                ('mouvmt_fin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dep.mouvmt_fin')),
                ('date_mvmt', models.DateField(auto_now_add=True)),
                ('montant_mvmt', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rapprochmt_bqe', models.BooleanField(default=False)),
            ],
            bases=('dep.mouvmt_fin',),
        ),
        migrations.CreateModel(
            name='Mouvmt_engage',
            fields=[
                ('mouvmt_fin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dep.mouvmt_fin')),
                ('periode', models.CharField(choices=[('P', 'en pls fois'), ('L', 'solde a livraison'), ('M', 'Mois'), ('T', 'Trimestre'), ('S', 'Semestre'), ('A', 'Annuel')], default='M', max_length=1)),
                ('jour_ds_periode', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('mois_ds_periode', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
                ('montant_precedent', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('montant_annonce', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('effectif_ds_n_periode', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
            ],
            bases=('dep.mouvmt_fin',),
        ),
        migrations.AddField(
            model_name='mouvmt_fin',
            name='tx_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dep.transaction'),
        ),
        migrations.CreateModel(
            name='Achat_ligne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_liv', models.DateField(auto_now_add=True)),
                ('nature_achat', models.CharField(choices=[('F', 'Fourniture'), ('S', 'Service'), ('D', 'Bien Durable')], default='F', max_length=1)),
                ('tx_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dep.transaction')),
            ],
        ),
    ]
