# Generated by Django 3.2.5 on 2022-01-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0003_auto_20220124_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvmt_engage',
            name='horodate_dern_conv',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='achat_ligne',
            name='categorie_autre',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='achat_ligne',
            name='categorie_gest',
            field=models.CharField(blank=True, choices=[('ECO CONSO', 'Infos gen eco techno'), ('LOGMT', 'Logement'), ('COMM', 'Communications'), ('BQE', 'Finances'), ('ASSUR', 'Assurances'), ('A_GEST', 'Autre')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='achat_ligne',
            name='categorie_loisir',
            field=models.CharField(blank=True, choices=[('SPRT', 'Sport'), ('CULT', 'Culture'), ('VACNC', 'Vacances'), ('A_LOISIR', 'Autre')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='achat_ligne',
            name='categorie_prod',
            field=models.CharField(blank=True, choices=[('GEST PATRIM', 'Patrimoine'), ('SVF', 'Savoir Faire'), ('TRVX', 'Travaux/Répar'), ('DECO', 'Decoration'), ('COUTUR', 'Couture/Tricot')], default='', max_length=16),
        ),
    ]
