# Generated by Django 3.2.5 on 2022-01-25 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0004_auto_20220125_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvmt_courant',
            name='date_mvmt',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
