# Generated by Django 3.2.5 on 2022-01-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0005_alter_mouvmt_courant_date_mvmt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur_regulier',
            name='tel',
        ),
        migrations.AddField(
            model_name='fournisseur_regulier',
            name='adresse_mel',
            field=models.EmailField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='fournisseur_regulier',
            name='adresse_rue',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='fournisseur_regulier',
            name='adresse_ville',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='fournisseur_regulier',
            name='tel_contact',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='fournisseur_regulier',
            name='tel_magasin',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='mouvmt_fin',
            name='compte_bancaire',
            field=models.CharField(choices=[('F', 'Fortuneo'), ('C', 'CIC')], default='F', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='moyen_paiemt_utilise',
            field=models.CharField(choices=[('CB_A', 'CB Annie'), ('CB_M', 'CB Michel'), ('CVU_M', 'CV_A usage unique'), ('CVU_M', 'CV_M usage unique'), ('CVA_M', 'CV_A pls debits'), ('CVA_M', 'CV_M pls debits'), ('DAB', 'Retrait'), ('ESP', 'Espèce'), ('CHQ', 'Cheque'), ('VRMT', 'Virement'), ('PbP', 'Pay by Phone'), ('CASM', 'CasinoMax')], default='CB_M', max_length=5),
        ),
        migrations.AddField(
            model_name='transaction',
            name='versmt_initial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='achat_ligne',
            name='intitule',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='fournisseur_regulier',
            name='intitule',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='mouvmt_fin',
            name='moyen_paiemt',
            field=models.CharField(choices=[('CB_A', 'CB Annie'), ('CB_M', 'CB Michel'), ('CVU_M', 'CV_A usage unique'), ('CVU_M', 'CV_M usage unique'), ('CVA_M', 'CV_A pls debits'), ('CVA_M', 'CV_M pls debits'), ('DAB', 'Retrait'), ('ESP', 'Espèce'), ('CHQ', 'Cheque'), ('VRMT', 'Virement'), ('PbP', 'Pay by Phone'), ('CASM', 'CasinoMax')], default='CB_M', max_length=5),
        ),
        migrations.AlterField(
            model_name='mouvmt_fin',
            name='nature_paiemt',
            field=models.CharField(choices=[('ORD', 'Integral'), ('ACC', 'Accompte'), ('ETA', 'Etalement'), ('SOL', 'Solde'), ('ARH', 'Arrhes')], default='ORD', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mode_reglmnt',
            field=models.CharField(choices=[('CPT', 'Immediat'), ('ETA', 'Etalmt'), ('CRE', 'Credit')], default='CPT', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='nature_tx',
            field=models.CharField(choices=[('UNIT', 'Unitaire'), ('LIV', 'A Livraison'), ('ABMT', 'Abonnement')], default='UNIT', max_length=4),
        ),
    ]
