# Generated by Django 3.2.5 on 2022-01-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0006_auto_20220128_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='moyen_paiemt_utilise',
        ),
    ]
