# Generated by Django 3.2.5 on 2022-01-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0008_transaction_intitule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='intitule',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
    ]
