# Generated by Django 3.2.5 on 2022-02-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0010_auto_20220201_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat_ligne',
            name='intitule',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='fournisseur_regulier',
            name='intitule',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fournisseur',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='intitule',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
