# Generated by Django 3.2.5 on 2022-02-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0011_auto_20220202_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur_regulier',
            name='intitule_tx',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='achat_ligne',
            name='categorie_fnmt',
            field=models.CharField(blank=True, choices=[('ALIM', 'Alimentation'), ('ENTRET', 'Entretien'), ('TOILET', 'Toilette'), ('SANTE', 'Sante'), ('ENERG', 'Energie'), ('VEMTS', 'Vetements'), ('DEPCMT', 'Deplacement'), ('A_FNMT', 'Autre')], default='', max_length=16),
        ),
    ]
