# Generated by Django 3.2.5 on 2022-02-03 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0012_auto_20220203_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil_achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(blank=True, default='', max_length=32)),
                ('nature', models.CharField(default='F', max_length=1)),
                ('categorie', models.CharField(blank=True, default='', max_length=16)),
                ('tx_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dep.transaction')),
            ],
        ),
    ]
