# Generated by Django 3.2.5 on 2022-02-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0013_profil_achat'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur_regulier',
            name='articles_hab',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='fournisseur_regulier',
            name='categorie_achat_hab',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='fournisseur_regulier',
            name='nature_achat_hab',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='fournisseur_regulier',
            name='intitule',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
