# Generated by Django 3.2.5 on 2022-02-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0014_auto_20220204_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur_regulier',
            name='groupe_hab',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fournisseur',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
