# Generated by Django 3.2.5 on 2022-02-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0015_auto_20220204_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat_ligne',
            name='groupe_achat',
            field=models.CharField(choices=[('FNMT', 'FNMT'), ('GEST', 'GESTION'), ('LOIS', 'LOISIR'), ('PROD', 'PROD'), ('AUTR', 'AUTRE')], default='FNMT', max_length=4),
        ),
    ]
