# Generated by Django 3.2.5 on 2022-02-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0016_achat_ligne_groupe_achat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achat_ligne',
            old_name='categorie_fnmt',
            new_name='categorie_achat',
        ),
        migrations.RemoveField(
            model_name='achat_ligne',
            name='categorie_autre',
        ),
        migrations.RemoveField(
            model_name='achat_ligne',
            name='categorie_gest',
        ),
        migrations.RemoveField(
            model_name='achat_ligne',
            name='categorie_loisir',
        ),
        migrations.RemoveField(
            model_name='achat_ligne',
            name='categorie_prod',
        ),
        migrations.AlterField(
            model_name='fournisseur_regulier',
            name='categorie_achat_hab',
            field=models.CharField(blank=True, choices=[('FNMT', [('ALIM', 'Alimentation'), ('ENTRET', 'Entretien'), ('TOILET', 'Toilette'), ('SANTE', 'Sante'), ('ENERG', 'Energie'), ('VEMTS', 'Vetements'), ('DEPCMT', 'Deplacement'), ('A_FNMT', 'Autre')]), ('GEST', [('ECO CONSO', 'Infos gen eco techno'), ('LOGMT', 'Logement'), ('COMM', 'Communications'), ('BQE', 'Finances'), ('ASSUR', 'Assurances'), ('A_GEST', 'Autre')]), ('LOIS', [('SPRT', 'Sport'), ('CULT', 'Culture'), ('VACNC', 'Vacances'), ('A_LOISIR', 'Autre')]), ('PROD', [('GEST PATRIM', 'Patrimoine'), ('SVF', 'Savoir Faire'), ('TRVX', 'Travaux/Répar'), ('DECO', 'Decoration'), ('COUTUR', 'Couture/Tricot')]), ('AUTR', 'AUTRE')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='fournisseur_regulier',
            name='groupe_hab',
            field=models.CharField(blank=True, choices=[('FNMT', 'FNMT'), ('GEST', 'GESTION'), ('LOIS', 'LOISIR'), ('PROD', 'PROD'), ('AUTR', 'AUTRE')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='fournisseur_regulier',
            name='nature_achat_hab',
            field=models.CharField(blank=True, choices=[('F', 'Consommable'), ('S', 'Service'), ('D', 'Bien Durable'), ('A', 'Autre')], default='', max_length=1),
        ),
    ]
