# Generated by Django 3.2.5 on 2022-02-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0017_auto_20220204_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat_ligne',
            name='nature_achat',
        ),
        migrations.RemoveField(
            model_name='fournisseur_regulier',
            name='intitule_tx',
        ),
        migrations.RemoveField(
            model_name='fournisseur_regulier',
            name='nature_achat_hab',
        ),
        migrations.AddField(
            model_name='fournisseur_regulier',
            name='objet_tx_hab',
            field=models.CharField(blank=True, default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='transaction',
            name='objet_tx',
            field=models.CharField(choices=[('F', 'Consommable'), ('S', 'Service'), ('B', 'Bien Durable'), ('D', 'Don'), ('A', 'Autre')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='achat_ligne',
            name='categorie_achat',
            field=models.CharField(blank=True, choices=[('FNMT', [('ALIM', 'Alimentation'), ('ENTRET', 'Entretien'), ('TOILET', 'Toilette'), ('SANTE', 'Sante'), ('ENERG', 'Energie'), ('VEMTS', 'Vetements'), ('DEPCMT', 'Deplacement')]), ('GEST', [('ECO CONSO', 'Infos gen eco techno'), ('LOGMT', 'Logement'), ('COMM', 'Communications'), ('BQE', 'Finances'), ('ASSUR', 'Assurances'), ('A_GEST', 'Autre')]), ('LOIS', [('SPRT', 'Sport'), ('CULT', 'Culture'), ('VACNC', 'Vacances')]), ('PROD', [('GEST PATRIM', 'Patrimoine'), ('SVF', 'Savoir Faire'), ('TRVX', 'Travaux/Répar'), ('DECO', 'Decoration'), ('COUTUR', 'Couture/Tricot')]), ('CAD', [('VRMT', 'Virement pour'), ('ESPC', 'Liquide pour'), ('ACHA', 'Achat pour'), ('ABMT', 'Abmt pour'), ('OBJ', 'Don d1 objet')]), ('AUTR', 'Autre')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='achat_ligne',
            name='groupe_achat',
            field=models.CharField(choices=[('FNMT', 'Fnmt'), ('GEST', 'Gestion'), ('LOIS', 'Loisir'), ('PROD', 'Prod'), ('CAD', 'Cadeau')], default='FNMT', max_length=4),
        ),
        migrations.DeleteModel(
            name='Profil_achat',
        ),
    ]
