# Generated by Django 3.2.5 on 2022-02-06 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0020_auto_20220206_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='objet_tx',
        ),
    ]
