# Generated by Django 3.2.5 on 2022-02-07 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0022_auto_20220207_0809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fournisseur_regulier',
            old_name='solo_tx',
            new_name='solo_tx_hab',
        ),
    ]
