# Generated by Django 3.2.5 on 2022-02-07 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0023_rename_solo_tx_fournisseur_regulier_solo_tx_hab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fournisseur_regulier',
            old_name='groupe_hab',
            new_name='groupe_achat_hab',
        ),
    ]
