# Generated by Django 3.2.5 on 2022-02-08 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0024_rename_groupe_hab_fournisseur_regulier_groupe_achat_hab'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvmt_fin',
            name='fin_validite_mp',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='achat_ligne',
            name='categorie_achat',
            field=models.CharField(blank=True, choices=[('FNMT', [('ALIM', 'Alimentation'), ('ENTRET', 'Entretien'), ('TOILET', 'Toilette'), ('SANTE', 'Sante'), ('ENERG', 'Energie'), ('VEMTS', 'Vetements'), ('DEPCMT', 'Deplacement')]), ('GEST', [('INFOS', 'Infos'), ('LOGMT', 'Logement'), ('INFQ', 'Informatique'), ('COMM', 'Communications'), ('BQE', 'Finances'), ('ASSUR', 'Assurances')]), ('LOIS', [('SPRT', 'Sport'), ('CULT', 'Culture'), ('VACNC', 'Vacances')]), ('PROD', [('GEST PATRIM', 'Patrimoine'), ('SVF', 'Savoir Faire'), ('TRVX', 'Travaux/Répar'), ('DECO', 'Decoration'), ('COUTUR', 'Couture/Tricot')]), ('AUTR', 'Autre ds le groupe')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='achat_ligne',
            name='groupe_achat',
            field=models.CharField(choices=[('FNMT', 'FNMT'), ('GEST', 'GESTION'), ('LOIS', 'LOISIR'), ('PROD', 'PROD'), ('AUTR', 'Autre groupe')], default='FNMT', max_length=4),
        ),
        migrations.AlterField(
            model_name='achat_ligne',
            name='nature_achat',
            field=models.CharField(choices=[('F', 'Consommable'), ('S', 'Service'), ('D', 'Bien Durable')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='fournisseur_regulier',
            name='categorie_achat_hab',
            field=models.CharField(blank=True, choices=[('FNMT', [('ALIM', 'Alimentation'), ('ENTRET', 'Entretien'), ('TOILET', 'Toilette'), ('SANTE', 'Sante'), ('ENERG', 'Energie'), ('VEMTS', 'Vetements'), ('DEPCMT', 'Deplacement')]), ('GEST', [('INFOS', 'Infos'), ('LOGMT', 'Logement'), ('INFQ', 'Informatique'), ('COMM', 'Communications'), ('BQE', 'Finances'), ('ASSUR', 'Assurances')]), ('LOIS', [('SPRT', 'Sport'), ('CULT', 'Culture'), ('VACNC', 'Vacances')]), ('PROD', [('GEST PATRIM', 'Patrimoine'), ('SVF', 'Savoir Faire'), ('TRVX', 'Travaux/Répar'), ('DECO', 'Decoration'), ('COUTUR', 'Couture/Tricot')]), ('AUTR', 'Autre ds le groupe')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='fournisseur_regulier',
            name='groupe_achat_hab',
            field=models.CharField(blank=True, choices=[('FNMT', 'FNMT'), ('GEST', 'GESTION'), ('LOIS', 'LOISIR'), ('PROD', 'PROD'), ('AUTR', 'Autre groupe')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='fournisseur_regulier',
            name='intitule_hab',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='fournisseur_regulier',
            name='moyen_paiemt_hab',
            field=models.CharField(choices=[('CB_A', 'CB Annie'), ('CB_M', 'CB Michel'), ('CVU_A', 'CV_A usage unique'), ('CVU_M', 'CV_M usage unique'), ('CVD_M', 'CV_A pls debits'), ('CVD_M', 'CV_M pls debits'), ('DAB', 'Retrait'), ('ESP', 'Espèce'), ('CHQ', 'Cheque'), ('VRMT', 'Virement'), ('SEPA', 'Prélèvmt Automatiq'), ('PbP', 'Pay by Phone'), ('CASM', 'CasinoMax')], default='CB_M', max_length=5),
        ),
        migrations.AlterField(
            model_name='fournisseur_regulier',
            name='nature_achat_hab',
            field=models.CharField(choices=[('F', 'Consommable'), ('S', 'Service'), ('D', 'Bien Durable')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='mouvmt_fin',
            name='moyen_paiemt',
            field=models.CharField(choices=[('CB_A', 'CB Annie'), ('CB_M', 'CB Michel'), ('CVU_A', 'CV_A usage unique'), ('CVU_M', 'CV_M usage unique'), ('CVD_M', 'CV_A pls debits'), ('CVD_M', 'CV_M pls debits'), ('DAB', 'Retrait'), ('ESP', 'Espèce'), ('CHQ', 'Cheque'), ('VRMT', 'Virement'), ('SEPA', 'Prélèvmt Automatiq'), ('PbP', 'Pay by Phone'), ('CASM', 'CasinoMax')], default='CB_M', max_length=5),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mode_reglmnt',
            field=models.CharField(choices=[('CPT', 'Comptant'), ('ETA', 'Etalmt'), ('CRE', 'Credit')], default='CPT', max_length=3),
        ),
    ]
