# Generated by Django 3.2.5 on 2022-02-11 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0025_auto_20220208_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date_tx',
            new_name='date_tx_enrgt',
        ),
    ]
