# Generated by Django 3.2.5 on 2022-02-11 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0026_rename_date_tx_transaction_date_tx_enrgt'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_tx',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
