# Generated by Django 3.2.5 on 2022-02-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0028_alter_achat_ligne_date_liv'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='renouv_auto_tx',
            field=models.BooleanField(default=False),
        ),
    ]
