# Generated by Django 3.2.5 on 2022-02-18 13:45

import dep.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0029_transaction_renouv_auto_tx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur_regulier',
            name='moyen_paiemt_hab',
            field=models.CharField(choices=[('CB_A', 'CB Annie'), ('CB_M', 'CB Michel'), ('CVU_A', 'CV_A usage unique'), ('CVU_M', 'CV_M usage unique'), ('CVD_M', 'CV_A pls debits'), ('CVD_M', 'CV_M pls debits'), ('DAB', 'Retrait'), ('ESP', 'Espèce'), ('CHQ', 'Cheque'), ('VRMT', 'Virement'), ('SEPA', 'Prélèvmt Automatiq'), ('PbP', 'Pay by Phone'), ('CASM', 'CasinoMax'), ('AVOIR', 'Avoir')], default='CB_M', max_length=5),
        ),
        migrations.AlterField(
            model_name='fournisseur_regulier',
            name='nature_tx_hab',
            field=models.CharField(blank=True, choices=[('UNIT', 'Unitaire'), ('LIV', 'A Livraison'), ('ABMT', 'Abonnement'), ('RBSM', 'Remboursement')], default='F', max_length=4),
        ),
        migrations.AlterField(
            model_name='mouvmt_courant',
            name='date_mvmt',
            field=models.DateField(blank=True, default=dep.models.MdcUtils.laVeille),
        ),
        migrations.AlterField(
            model_name='mouvmt_fin',
            name='moyen_paiemt',
            field=models.CharField(choices=[('CB_A', 'CB Annie'), ('CB_M', 'CB Michel'), ('CVU_A', 'CV_A usage unique'), ('CVU_M', 'CV_M usage unique'), ('CVD_M', 'CV_A pls debits'), ('CVD_M', 'CV_M pls debits'), ('DAB', 'Retrait'), ('ESP', 'Espèce'), ('CHQ', 'Cheque'), ('VRMT', 'Virement'), ('SEPA', 'Prélèvmt Automatiq'), ('PbP', 'Pay by Phone'), ('CASM', 'CasinoMax'), ('AVOIR', 'Avoir')], default='CB_M', max_length=5),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_tx',
            field=models.DateField(blank=True, default=dep.models.MdcUtils.laVeille),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='nature_tx',
            field=models.CharField(choices=[('UNIT', 'Unitaire'), ('LIV', 'A Livraison'), ('ABMT', 'Abonnement'), ('RBSM', 'Remboursement')], default='UNIT', max_length=4),
        ),
    ]
